### PR TITLE
Fixes opening view in Android + extra permanent loading page in Android.

### PR DESCRIPTION
**Pull request by a-fortunato**
> This fixes the problem indicated in next comment: [xcarpentier#69 (comment)](https://github.com/xcarpentier/rn-pdf-reader-js/issues/69#issuecomment-536482614).
> To work it needed permissions to read files plus the property allowFileAccessFromFileURLs from WebView, but we thought it might be more of an interesting idea if all the saving and loading data to and from a file were skipped, so the html is sent directly to the WebView.

This PR also fixes a permanent extra loading page in android.

Please let me know if there's anything wrong or if you need a wider explanation.

### CODE REVIEW

**Comment by Xanewok** [comment]
:wave: @xcarpentier 

I can confirm the fix and the change is fairly straightforward - would it be possible for you to merge this if you don't find any issues with it and possibly do a release including the fix? That'd be great :heart_eyes: 

Right now I'm pulling a git dependency off the https://github.com/Codeko/rn-pdf-reader-js fork but would be great to just pull the release package instead :smile:

**Comment by wardjk87** [comment]
This solution helped me improve my use of the plugin in my Expo 35 android version. Specifically, I just re-created the plugin in part from this PR and my changes for getting IOS to work.

**Comment by xcarpentier** [comment]
Should be fixed at `v0.5.0`.

**Comment by Xanewok** [comment]
Thank you so much!

**Pull request closed without merging**
