### PR TITLE
Zoom and Pan Suggestion #20

### PR DESCRIPTION
**Pull request by ColinKrist**
Apologies for a lot of random stuff. My linter added a bunch of things automatically. 

There is no scrolling between pages via guestures like you had before. This had to be removed to make way for panning your zoomed in page. I need standardized color suggestions for the number backgrounds and navigation backgrounds. Leaving them transparent isn't a great user experience against white pages. I left my project's coloring in there, but change them to whatever you need them to be.

### CODE REVIEW

**Comment by xcarpentier** [comment]
Awesome 🎉

**Comment by xcarpentier** [comment]
Will try it tomorow !

**Comment by thu-sama** [comment]
@xcarpentier 
@ColinKrist 
Thank you for nice plugin and zooming.
I wonder when will this pull request be merged?

**Comment by xcarpentier** [comment]
@thu-sama sorry have not yet tested it.
I will and try to merge and publish on npm soon.
BTW I think I will upgrade react-pdf too to benefits on last pdf.js and improve stuff in react.

**Pull request closed without merging**
